# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Want A Scene
email: dad13@naver.com
description: > # this means to ignore newlines until "baseurl:"
  Wonho Shin Photography.
  Located in Seoul.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://wantascene.github.io" # the base hostname & protocol for your site
twitter_username: wantascene
github_username:  wantascene

# Build settings
markdown: kramdown
gems: [directory_tag]